### ISSUE TITLE
安装失败 ,依赖冲突

### ISSUE THREAD

**Issue by rxrddd** [nsnake/playcat-queue-webman#1]
![image](https://github.com/nsnake/playcat-queue-webman/assets/30316411/0fca48a4-e6ac-4660-bba0-a451a981dc91)

看错误信息好像是playcat/queue-base的依赖和我项目的依赖版本冲突了  请教一下这个应该如何解决?

**Comment by nsnake** [comment]
已经更新了，使用最新版即可
