### ISSUE TITLE
运行报错，ProducerData的serializeData返回类型错误

### ISSUE THREAD

**Issue by JingFang-i** [nsnake/playcat-queue-webman#2]
**环境**：
playcat/queue-webman 1.0.1
php 7.4
webman v1.5.16

**描述**：
Playcat\Queue\Protocols\ProducerData的serializeData方法返回值不是array，msgpack_pack函数的返回值是string

**运行报错**：
![image](https://github.com/nsnake/playcat-queue-webman/assets/62050955/1a08d2f2-3e96-4546-a56e-4169bb78e898)

**Comment by nsnake** [comment]
ok，已经定位到问题了，下版本修复

**Comment by nsnake** [comment]
已修复。从compser在安装下即可
